### ISSUE TITLE
Add support for multi-root workspaces

### ISSUE THREAD

**Issue by lostintangent** [vsls-contrib/codetour#1]
Currently, we only discover code tours for the first root in the currently opened workspace. This probably accommodates most scenarios, but we should ensure that devs can open multiple workspaces, and see the tours available across them all.

**Comment by abulka** [comment]
Confirmed - e.g. vers 0.0.11 - local project, local install.  No playback if project is part of a workspace.  Even when I tried with the first project of the workspace it didn't playback.

When I reopened my project directly (not as part of the workspace) my recordings were gone. But recreating the recordings and playing them back worked OK.

**Comment by alvaromartmart** [comment]
I can also confirm the extension does not work for me on workspaces

**Comment by lostintangent** [comment]
This has been resolved in the latest extension update. Thanks for the feedback and let me know if you have any feedback 👍
