### ISSUE TITLE
CodeTour icon in the gutter goes berzerk 🔥

### ISSUE THREAD

**Issue by johnpapa** [vsls-contrib/codetour#142]
Notice what happens in the GIF below to the gutter (where the codetour icon appears) when I replace the text in a file that has a codetour file reference

![2021-03-09_11-05-32 (1)](https://user-images.githubusercontent.com/1202528/110500942-b21ca100-80c7-11eb-89dd-2b915baed9c3.gif)

**Comment by lostintangent** [comment]
Thanks for reporting this! I've got a fix and will ship an update in just a bit. Stay tuned!
