### ISSUE TITLE
Allow defining a tour "welcome page"

### ISSUE THREAD

**Issue by johnpapa** [vsls-contrib/codetour#26]
Thinking out loud ... 

The tour begins and the first thing the audience sees is a welcome message. Something to give them context for the tour and tell them what they are about to see.

Title: Welcome to the Tour of Heroes!
Body (multi-line): Here we can put paragraphs using markdown to explain the tour. Good tips might be to explain the path we are taking through the tour. What we're trying to get across. What they will be oriented with.
Author: Name
Tour Lat Revision Date:

**Comment by lostintangent** [comment]
I really like this suggestion! After I finish some of the core UX improvements, this seems like an awesome enhancement to the current experience 👍

**Comment by alvaromartmart** [comment]
Great idea!

Could this concept be expanded even more by introducing something like "step templates"? I'm thinking on something like Github's issue templates... the users could add to the project one or several markdown files containing a template for new tours/steps.

**Comment by lostintangent** [comment]
@alvaromartmart I like that idea too! Maybe we could create a different issue to track that enhancement? I interpret this issue as allowing you to record a “step 0” that isn’t associated with any specific file/line of code, and would allow you to orient the reader with what they’re about to see.

Whereas the notion of a “step template” would enable easier authoring, when a team uses a very similar style for tours. Does that seem accurate?

**Comment by lostintangent** [comment]
I’m looking at using the “Svelte Compiler Handbook” as a test case for CodeTour, and it includes an intro section. So I agree that this would be super valuable to add.

**Comment by lostintangent** [comment]
Thinking out loud here: what if instead of implementing a “welcome page”, we simply introduced the notion of “markdown steps” that allow you to write arbitrary markdown that will be displayed to the reader and doesn’t need to be associated with code. That way, you could use it for a welcome page, but it could also serve as a “wrap up” page, or for providing conceptual explanations within a tour.

I kind of like this approach, since it’s a general purpose primitive that could be used for a variety of purposes. I also think we’ll have other “step types”, and so this starts to move us in that direction. Thoughts?

**Comment by lostintangent** [comment]
Hey all! I just shipped an extension update that introduces [content steps](https://github.com/vsls-contrib/codetour#content-steps), which are steps that include a title and markdown, but aren't associated with a directory or file. When you start recording a tour, the `CodeTour` tree includes a new node called `Add tour step...` underneath the recording tour. When you click that, it asks you for a title, and then lets you create a "content-only" step. This can be used to define not only a "welcome page", but also, any intermediate explanations within a tour, that don't need to be associated with code.

Let me know if you have any thoughts on the experience. Thanks! 👍
