### ISSUE TITLE
Add “Stop Tour” command

### ISSUE THREAD

**Issue by alefragnani** [vsls-contrib/codetour#29]
Today, once you start a tour, there is no way to “stop”. 

I know you can “pause” clicking the ^ icon in the comment/step panel, but it only hides the tour, but keeps the “comment indicator” in the gutter.

The “Stop Tour” command should end the tour entirely, removing the indicator from the gutter and resetting the Status Bar.

**Comment by lostintangent** [comment]
I just pushed a `Code Tour: End Tour` command and will publish an update to the store this afternoon 👍

**Comment by lostintangent** [comment]
This change has just been published to the marketplace!
