### ISSUE TITLE
Allow visually editing existing tours

### ISSUE THREAD

**Issue by lostintangent** [vsls-contrib/codetour#3]

**Comment by RPDeshaies** [comment]
Is there a "non-visual" way to do it right now?

**Comment by lostintangent** [comment]
@RPDeshaies You could crack open the JSON file in the `.vscode/tours` folder and edit it manually. It wouldn't be super hard to do, but not necessarily ideal :)

**Comment by RPDeshaies** [comment]
That what I started doing since I was not sure if there was a UI for it. 
Anyway, I agree having a UI for it would be "more ideal" like your saying!

Little parentheses: this extension looks incredible and super useful.

**Comment by lostintangent** [comment]
This has now been shipped! You can now edit a tour by simply right-clicking a tour in the `CodeTour` tree and select `Edit Tour`, and/or clicking the pencil icon in the comment UI of a tour you're actively viewing. Would love to hear any feedback!
