### ISSUE TITLE
Focus cursor on steps 

### ISSUE THREAD

**Issue by alefragnani** [vsls-contrib/codetour#30]
When you start a tour, the cursor should follow/focus the step position (line). 

This would be really helpful if you use a Code Tour not only for navigation purposes, but also when you create a Code Tour which guides the user for “required changes” on files.

**Comment by johnpapa** [comment]
#23 duplicate

closed and coming soon

**Comment by lostintangent** [comment]
Yep I'm hoping to ship this change soon!

**Comment by alefragnani** [comment]
I’m sorry, but this is not a duplicate.

#23 ask to focus “in the comment panel” to start typing the comment/step details when you are recording a Code Tour. What I’m asking is to focus “in the document” on each step, when you “Start a Tour”.

Could it be reopened?

**Comment by johnpapa** [comment]
Good point. When records f a tour focus should go to the text box. 

When playing a tour - should focus go to the reply box? I think that is ok as long as we get keyboard shortcuts to navigate back and forward.

**Comment by alefragnani** [comment]
I’m not sure about the reply box. I think it depends on the reason behind your Code Tour:

1. A project walkthrough: You want to navigate through points of interest in your project, and maybe the user could update the source code
1. A threading/comment system: You want to navigate AND reply to comments/ideas added as steps.

My first idea when I saw Code Tour was number 1, but of course, number 2 is also a great scenario. And I’m sure others will see more reasons 😁

**Comment by lostintangent** [comment]
This has been fixed in master and I'll ship a marketplace update in the next hour or so 👍
