### ISSUE TITLE
Replace the “stop” icon in Side Bar

### ISSUE THREAD

**Issue by alefragnani** [vsls-contrib/codetour#31]
The `Stop Tour` icon which appears in the Side Bar gave me the wrong idea of `Delete Tour`. This happened because the **X** icon is used on other places in VS Code as a delete node element.

I think that because the `Start Tour` icon uses the **play** icon, like the `Start Debugging`, the `Stop Tour` icon could use the **square** icon, just like the `Stop` debugging.

Thank you

**Comment by lostintangent** [comment]
This has now been fixed, and will be released in an upcoming release this evening. Keep the awesome feedback coming!

**Comment by alefragnani** [comment]
Thank you for this great extension. It’s a pleasure to contribute!

**Comment by lostintangent** [comment]
@alefragnani Thanks so much for all of your feedback! Please keep the feedback coming and let me know how I can make this extension experience awesome 🙌
