### ISSUE TITLE
Steps should automatically be in edit mode when recording

### ISSUE THREAD

**Issue by abulka** [vsls-contrib/codetour#34]
When playing back a tour, hitting Ctrl Rightarrow is supposed to step you through the steps.  It does for the first step then it stops working, and Ctrl Rightarrow starts moving the cursor through the code instead? I think its a focus issue - if you click to focus on the step window then Ctrl Rightarrow works again for the next step.

The highlight in the tree does not match what is being displayed in the code window, when navigation has been done using arrow buttons. This would be most helpful to know where you are.

Clicking on the arrow buttons in the tree seem to do illogical things. Sometimes they just highlight the step represented by the explorer window, sometimes they cause the next or previous step to appear. Can't figure out their logic.

Clicking on the arrows in the current step window work OK, but it would be nice if the corresponding tree explorer step would highlight, as mentioned before.

**Comment by lostintangent** [comment]
Thanks for this feedback! I just published an extension update that addresses two things:

1. By default, the ctrl+right/ctrl+left arrows work as expected when navigating a tour. If you explicitly focus your cursor into the editor, then this keybinding no longer works, because ctrl+right/ctrl+left is already used to move the cursor to the beginning/end of the line. That said, focus is always placed on the comment UI when navigating a tour, and therefore, a user could the arrow keys to navigate forwards and backwards in ease, without having the inconsistent behavior we previously had.

2. The `CodeTour` tree view is now kept in sync with the current tour step, to make it easy to visualize where in the tour you're at. Here's a gif that demonstrates the new behavior

   <img width="600px" src="https://user-images.githubusercontent.com/116461/76807453-a1319c00-67a1-11ea-9b88-7e448072f33d.gif" />

So those two points should hopefully be addressed, and I'd love to hear your feedback! To your last comment: the up/down arrows in the tree view are actually there to allow you to re-arrange the steps in the tour, not to navigate you from one step to the other. If you have any thoughts on that UX, and how to make it more intuitive, I'd love to hear it 👍

**Comment by abulka** [comment]
That's MUCH nicer now - thanks. And apologies for misinterpreting the up/down arrows in the treeview - I think the GUI is OK for moving steps.

Re UX feedback - it would be nice to have an 'edit tour' button in the codetour explorer. It seems more sensible there than having to click on an arbitrary individual step to enter 'edit mode' for the entire tour.

Editing a step is a little confusing too - I need to hit the edit button on the step, then again on the ... button and then click 'edit step'.  Perhaps the edit button on the step throws you into edit step mode directly?

**Comment by lostintangent** [comment]
Hey! If you right-click a tour in the tree, there is already an “Edit Tour” menu item. That said, I could also add an “Edit Step” menu item to jump straight to editing a specific step, and I can also update the edit action to put each step into edit mode directly. Would that work?

**Comment by abulka** [comment]
Ah OK re the right click trick to 'Edit Tour' - I didn't notice that.  A separate edit icon next to the play button I think still would be ideal - together with a more prominent 'editing mode' - like only showing the move up/move down buttons of the explorer whilst in editing mode. At the moment those editing buttons are always visible and upon reflection, I guess that's why I initially got confused thinking they were navigation arrows, because those editing/move step buttons are visible and functional in playback mode.

> adding an “Edit Step” menu item to jump straight to editing a specific step

Yes, plus perhaps once in 'editing mode' plain clicking on any step would also do that behaviour.

> I can also update the edit action to put each step into edit mode directly

Yes, that would be great, and by pressing on it you would switch from playback to 'editing mode', meaning as you jump from step to step (either via left and right arrow on each step, or via the explorer) you are always automatically in editing mode when you land on each step.

Finally, if there is a more prominent 'editing mode' thus a clearer distinction between playback and editing - then to exit editing mode, the red 'end tour' button should probably be replaced with an 'end edit' button on both the step and in the explorer, whilst in 'editing mode'. At the very least, the tooltip on all "End Tour" buttons should be reworded to say 'end edit' whilst in editing mode, because 'ending the tour' to 'exit editing' I think is confusing.

**Comment by lostintangent** [comment]
FYI, I added an “Edit Step” context menu to the tour tree and I also updated the tree to only show the buttons for rearranging steps while you’re actively recording.

That said, I’m going to repurpose this issue to be specific to putting the steps in edit mode automatically while in edit mode. Let me know if that makes sense 👍

**Comment by abulka** [comment]
Sounds good 👍

**Comment by lostintangent** [comment]
The bug fix for this was checked into VS Code, and so I was finally able to take advantage of this 😄 Thanks for the feedback and let me know if you run into any other issues/questions 👍

**Comment by abulka** [comment]
Is that version `0.0.25` of the extension? In that version, r.click selecting 'edit step' on a tree item puts me in 1st level 'edit tour' editing mode - I still need to click on '...' (more actions) and select 'edit step' a  second time in order to actually edit the text of a step.  Thus strictly speaking, the tree item popup menu should really be 'edit tour'.

My preference is that r.click selecting 'edit step' on a tree item puts me in deep, proper edit step mode on that step, allowing me to edit the text immediately - not just put me in 'edit tour' mode (which I find pointless). And there should be an icon on the tree toolbar which will 'edit step'.

I generally think having a two layered 'edit tour'  and 'edit step' mode is confusing. I sort of get it now, after playing with it repeatedly, but it never feels natural. Just my 2c.

Thanks for the changes so far!

**Comment by lostintangent** [comment]
This change is in 0.0.26, and removes the “double edit”. Let me know what you think!

**Comment by abulka** [comment]
Ok my extensions updated themselves and I was finally able to test version `0.0.26` editing. 

Nice - the removal of the "double edit" is such a great decision - the extension feels 10x more usable and now feels 'normal' to use. Thank you!
