### ISSUE TITLE
Editing a step does not allow change of selection

### ISSUE THREAD

**Issue by abulka** [vsls-contrib/codetour#35]
When editing a step, you can edit the text OK but changing the selection does not get saved. It would be nice if you can adjust the selection - otherwise you are stuck forever with a erroneous selection.

**Comment by lostintangent** [comment]
Agreed! I’ll prioritize this fix this week 👍

**Comment by lostintangent** [comment]
This has been fixed in the latest update. If you edit a step, and then change (or remove) the selection, that will be recorded when you save those changes (along with any changes to the step's description). Thanks for the feedback here!

**Comment by abulka** [comment]
Thanks for this fix.  P.S. Would be nice to be able to edit/adjust the step line number too!

**Comment by lostintangent** [comment]
Agreed! I just filed this issue to track that additional enhancement: https://github.com/vsls-contrib/codetour/issues/36. If you have any thoughts on how the user experience could work, I’d love to hear it, since I’m not immediately sure how to best enable this. Thanks!
