### ISSUE TITLE
Allow visually editing the line number associated with a step

### ISSUE THREAD

**Issue by lostintangent** [vsls-contrib/codetour#36]
Using the tour recorder, you can edit the description and selection that’s associated with a step. However, in order to edit the line number that the step comment is displayed on, you need to manually edit the tour’s JSON file. We should explore how to enable easily editing a step’s line number via the recorder, so that core authoring operations don’t require editing JSON files directly .

**Comment by abulka** [comment]
In terms of UX, here are some thoughts:

- dragging the step could be a way to change the line number although that could prove difficult to implement.  
- up down arrows to 'nudge' the line number into the desired location. 
- an edit box with the line number, allowing direct entry/editing of the line number value you want.

**Comment by lostintangent** [comment]
Thanks for the suggestions! Based on the current support in VS Code, I wouldn’t be able to do drag and drop unfortunately. But the other two options are doable, so I’ll explore what we can do here. Stay tuned! 👍

**Comment by abulka** [comment]
When editing a step, the `...` more actions drop down currently lists `move up` and `delete step`. 

I don't use `move up` because if I want to move a step I'll use the tree.  What if `move up` and a new `move down` nudge the step up and down a line - as adjusting the position of the step is exactly what I expect and want at this point. 

An addition menu item `move to line...` could prompt for a new line number to move the step to.

**Comment by alpaix** [comment]
+1 on ability to drag the step within the file to a desired location. Ultimately, it'd be the most intuitive experience.

**Comment by lostintangent** [comment]
This feature has now been checked in. Unfortunately, VS Code doesn't support any sort of drag-and-drop experience. However, as suggested by @abulka, when you're editing a step, you can click the `...` menu, select `Change Line`, and then specify the new line number.

Furthermore, if your step also has a selection associated with it, you can run `Change Line` and remove the line number, which will "lock" the step to the final line of the selection. You can also create new "selection steps" by selecting a block or text, right-clicking the editor and selecting `Add CodeTour Step`.

I'm going to close this issue as resolved due to this enhancement, but please let me know if you have any feedback on the aforementioned improvements. Thanks!
