### ISSUE TITLE
Improve onboarding experience

### ISSUE THREAD

**Issue by gsmile** [vsls-contrib/codetour#41]
Currently, the list of tours is blank when a dev installs the extension. During testing, when we showed the extension with a sample tour to a dev, it helped them orient to the extension functionality and UI.

**Comment by Davepar** [comment]
I did the following steps:
* Uninstalled the CodeTour extension and restarted VSCode
* Opened a workspace that contained tours (in .tours)
* Installed the CodeTour extension

The "Start Code Tour" button appeared in the status bar. Do you want the list of tours to appear somewhere else, or did I miss a step?

**Comment by gsmile** [comment]
I deleted a comment by mistake. To clarify: I am working towards showing a default sample tour when the extension is installed.

**Comment by lostintangent** [comment]
FYI, I just pushed an update that makes the `CodeTour` tree always visible, and provides a helpful "welcome message" to simplify the getting started experience.

![image](https://user-images.githubusercontent.com/116461/83283871-c2930900-a190-11ea-9f9b-f3bae503d251.png)

**Comment by lostintangent** [comment]
I’m going to close this issue as resolved per my previous comment. However, we should explore whether we need to do more in order to improve the onboard experience.
