### ISSUE TITLE
Show that a line has a codetour associated outside of "tour mode"

### ISSUE THREAD

**Issue by stefanforsberg** [vsls-contrib/codetour#45]
I think it might be helpful to be able to see that a file you're currently viewing has a code tour step associated with it even though you're not currently viewing a tour.

So in tour mode:
![image](https://user-images.githubusercontent.com/358570/77993080-a78a5100-7327-11ea-8123-2ec6b7d71aed.png)

Not in tour mode
![image](https://user-images.githubusercontent.com/358570/77993215-f0daa080-7327-11ea-9e0e-3a9f71a85bf0.png)

It can serve as a hint that this thing might be important and by clicking it you can start the tour at that step and learn why. Might also be helpful as a reminder that if you edit this file you might need to update some line number for the hint itself 😅

**Comment by lostintangent** [comment]
Hey! I was tracking this already via #17, but I like the detail/screenshots you provided better 😄 So I'll close that issue and we can use this one to track progress 👍

**Comment by lostintangent** [comment]
I just shipped an extension update with support for "tour markers". The UX might benefit from some tweaking, so I'd love to hear any feedback 👍 

![Markers](https://user-images.githubusercontent.com/116461/78101204-9aa74500-739b-11ea-8a1e-dea923910524.gif)
