### ISSUE TITLE
Allow recording code span highlighting

### ISSUE THREAD

**Issue by lostintangent** [vsls-contrib/codetour#5]
Currently, you can select a line of code and attach a comment to it. However, you may want to highlight a multi-line span of code and annotate that. We should explore how to introduce support for doing that.

**Comment by ShaunWMusic** [comment]
yes! I agree this would be very useful as I use this feature in Github reviews quite often now.

**Comment by lostintangent** [comment]
This has been checked into master and will be released this afternoon.
