### ISSUE TITLE
Export notebook as HTML

### ISSUE THREAD

**Issue by LucianoBestia** [vsls-contrib/codetour#54]
I like very much the "View Notebook".
Is it possible to export that as html or markdown to a local file ?
I hope it retains the same graphic style.

![image](https://user-images.githubusercontent.com/31509965/79968412-ade69580-84ad-11ea-9ced-9a98881202ea.png)

**Comment by lostintangent** [comment]
@LucianoBestia This is a great idea! It would be a pretty significant feature though, since I’m relying heavily on VS Code’s native notebook tenderer for this, and I’d have to replicate all of that. 

Out of curiosity, could you share what you had in mind with being able to export it? Sharing it with others that aren’t using VS Code?

**Comment by LucianoBestia** [comment]
A software project can be viewed from many different angles, depends on the persons interaction with it. Every role needs some explanation in a form of a book/tutorial/manual,...
For the app user, there must be a user manual or something like this.
For the developer they need a reference documentation and a (more or less) explanatory readme.md.
Also code comments are essential.
But none of these is really adequate for understanding the code flow. It is ok for using the code as a library, but not to engage into understanding and modifying the code.
Writing a book for the "code flow" is absolutely a nightmare. The code changes fast, and is impossible to keep all the code fragments in the book in sync with the actual code. So in 5 minutes that book is obsolete and mostly unusable or at least  deceiving.
Your extension CodeTour makes a breakthrough in this area. Instead of copying static code fragments into a text document, you have the opposite direction: virtually add text to the code. So the code is always in sync. The text don't change so often, really, because the code is a lot self-explanatory. The most important part is the sequence of steps to teach a mental image of the code flow to another person. That sequence does not exist in the code itself. Not on a high level for quick human understanding.
Not every developer has VSCode. So a generated static html "book" file looks great to share knowledge with others. I like very much the dark design of the "notebook". The same code is also available on GitHub, so it could be easy to add a link and jump from the notebook to Github code.
Thank you. Great job.

**Comment by LucianoBestia** [comment]
Sorry for closing, Wrong button.

I don't really know much about VSCode, but in essence it is a web browser.
So I would expect, that what we see on the screen is rendered HTML+css. 
And maybe there is a method to export that underlying HTML. 
I don't know. I just wish.

**Comment by LucianoBestia** [comment]
I discuss the same also in issue https://github.com/vsls-contrib/codetour/issues/55.
I will close this issue.
