### ISSUE TITLE
Text Entry Box does not respond to certain keyboard presses like Backspace

### ISSUE THREAD

**Issue by zammew** [vsls-contrib/codetour#58]
Hi,

This bug does not always happen when adding the steps, but once it happens, you need to restart vscode so that keyboard buttons like backspace, delete, home, end work again

![backspace](https://user-images.githubusercontent.com/53103250/80274452-036cad80-870d-11ea-9add-27aa752fe14a.gif)

**Comment by gsmile** [comment]
Hi there, thank you for letting us know! Can you share what OS / version you are using? Thank you!

**Comment by lostintangent** [comment]
I was able to confirm that this is a bug in VS Code, not CodeTour. If you could file an issue on their [repo](https://github.com/microsoft/vscode), that would be hugely appreciated. In the meantime, I’m going to close this issue as being external. Thanks!
