### ISSUE TITLE
Allow referring to another tour from within a tour

### ISSUE THREAD

**Issue by OzTK** [vsls-contrib/codetour#68]
It would be awesome to be able to refer to another tour inside a step and allow to start it when clicking on that reference.

It could be very similar to a regular link (maybe with a special URL?) except it would start the referenced tour when clicking on it.

**Comment by lostintangent** [comment]
Someone requested the exact same thing on Twitter [yesterday](https://twitter.com/homol/status/1259891624672399360?s=21) 😁 Though they were asking to reference previous steps within the same tour.

In your case, would you simply want to reference the other tour, and when clicked, it would start the tour at step #1? Or would you also need to be able to start another tour at an arbitrary step?

Also, just to confirm: would the tours the referenced tours exist within the tour workspace? Or would you want to also be able to reference them by URL?

**Comment by RandomFractals** [comment]
@lostintangent  can you make it reference tours by url with # for the tour step to link to for this feature?

**Comment by OzTK** [comment]
In my specific case, I was writing a general tour for a project and then wanted to point the user at more specific ones to dive deeper into the codebase, so the idea was only to start another tour from the beginning, in the context of the same workspace.
But as @RandomFractals mentioned, I can totally see the benefit of being able to reference specific steps or tours by URL!

Unrelated, but thank you @lostintangent for the awesome work on that extension, onboarding can be such a difficult time where everything looks foreign, I'm hoping it will make the process a lot easier for our new hires 🙂

**Comment by lostintangent** [comment]
@OzTK Thanks! I’m thinking about adding a special syntax to a tour where you type “[[Tour Name]]” to automatically create a link to start the tour. Alternatively, you could type “[[Tour Name,Step Number]]” to start a tour at a specific step. Thoughts?

To fully accommodate all the possible use cases, “Tour Name” could also be a URL (in addition to a local tour name), and you could even omit the tour name, in order to refer to the current tour (e.g. “[[,5]]” to jump to the 5th step of the current tour).

**Comment by OzTK** [comment]
That API seems intuitive and easy to use. Seems like it would solve all the possible use-cases at the moment. It doesn't seem like `,` is disallowed in tour names though, so that may be tricky to parse

**Comment by RandomFractals** [comment]
@lostintangent why not just go with tour url and # for the step? would be easy to parse and add to tours.

**Comment by lostintangent** [comment]
@OzTK I just shipped an update that allows you to add "command links" to your steps, which are simply markdown links that reference VS Code commands, as opposed to URLs. As part of this change, I also introduced an auto-completion provider that makes it easy to perform common tasks, including the ability to navigate the user to another tour or step. If you take a look at the following gif, you'll see how you can add a command link, then select the `Start tour` option, and fill in the title of the tour you want to navigate the user to. That way, you can have your primary CodeTour, that then links to other tours in the same codebase.

![Commands](https://user-images.githubusercontent.com/116461/82712888-09877880-9c3e-11ea-953f-603fca2d7f64.gif)

I'm going to close this issue as resolved with this change, but please feel free to re-open it if this doesn't accomodate your use case, or if you run into any problems. Thanks again for the feedback!

**Comment by OzTK** [comment]
That's awesome! Thanks for the quick release of this @lostintangent. It's perfect, even more flexible that what I had in mind 🙂

**Comment by lostintangent** [comment]
Quick update! In addition to the flexible "command links" support I already added, I also just shipped support for step/tour references. Using this, you can add links to steps/tours using the following syntax: `[#23]` (to reference a step in the current tour), `[Tree View]` (to reference another tour by title), `[Tree View#3]` (to reference a specific step in another tour). If you want, you can also customize the display text that will be used for these links by appending the title to the link reference (e.g. `[Title][#23]`). You can find out more info [here](https://github.com/vsls-contrib/codetour#step-references).

This syntax is simply sugar on top of the more general command link approach, but I wanted to add a simplified way of enabling step/tour navigation, "on top" of a flexible foundation. I'd love to hear any feedback. Thanks!

**Comment by RandomFractals** [comment]
This is perfect. Very md like. Thanks for adding this convenient tour steps linking.
