### ISSUE TITLE
Tour glyphs duplicated beside editor

### ISSUE THREAD

**Issue by gsmile** [vsls-contrib/codetour#69]
Code Tour glyphs are repeating itself on the side of the screen. It can be reproduced by the following:
1. Start a tour. Cut the snippet of code surrounding an existing tour step (before and after)
2. Paste it into another location in the file
3. Cut that same snippet again
4. Paste back in original location

![image](https://user-images.githubusercontent.com/12738587/81846602-596c8e00-9520-11ea-8062-22889f89e701.png)

**Comment by lostintangent** [comment]
This issue should now be fixed 👍

**Comment by gsmile** [comment]
Great, thanks!
