### ISSUE TITLE
Code tour v0.0.28 doesn't work

### ISSUE THREAD

**Issue by hshruti** [vsls-contrib/codetour#75]
1. Code tour option is not visible in explore.
2. when new tour is create. Left line and + icon is not displayed any more. There is no way to add a steps

Reverting to v0.0.27 fixes above issue.

**Comment by lostintangent** [comment]
@hshruti Hmm, apologies for this issue. Are you on Windows by any chance? I just tried reproing this on my mac and a Linux box, and everything seems to work fine. I made some changes to the way that Uris are handled in v0.0.28, so it's possible that I broke Windows with that change :/

**Comment by alexweininger** [comment]
@lostintangent  Same issue here. I haven't been able to record a CodeTour on Windows. It works flawlessly on my Mac though, just like you said.

**Comment by hshruti** [comment]
@lostintangent  yes i am using windows

**Comment by hshruti** [comment]
@lostintangent  yes i am using windows

**Comment by rkeithhill** [comment]
Doesn't work for me either - on Windows 10 1909, VSCode 1.45.1.  I don't see the TOURS section in the File Explorer.  If I use the command palette to open a tour file and click on the status bar section `CodeTour: #0 of 0 (Add New Settting)`, I get this error:
![image](https://user-images.githubusercontent.com/5177512/83177765-e268f500-a0dc-11ea-9b1e-c790acde8533.png)

**Comment by lostintangent** [comment]
Apologies for the inconvenience here! I just shipped v0.0.29 which resolves this issue on Windows. Please me know if you're running into any other issues. Otherwise, things should be good to go 👍
