### ISSUE TITLE
Nothing shows up in Explorer

### ISSUE THREAD

**Issue by fredkuhne** [vsls-contrib/codetour#77]
Windows 10
VS Code 1.45.1

I installed the extension to try out adding a tour and don't see anything in explorer or any clear way in the UI of adding a tour. Any suggestions? I have already turned it off and back on. ;)

![image](https://user-images.githubusercontent.com/46819969/83271144-0edd4980-a18f-11ea-86b8-aa5e53f32cbe.png)

![image](https://user-images.githubusercontent.com/46819969/83271181-1a307500-a18f-11ea-917a-400a663e0a01.png)

**Comment by lostintangent** [comment]
Previously, the `CodeTour` tree would only show up if the opened workspace actually had any tours in it. So you'd have to use the `CodeTour: Record Tour` or `CodeTour: Open Tour` commands to create/view tours. That said, I just pushed an update that will always show the `CodeTour` tree on the `Explorer` tab, to make the experience more discoverable. Let me know if that seems to work well for you and/or if you have any other feedback. Thanks!

**Comment by fredkuhne** [comment]
Nice and super fast response. :)
