### ISSUE TITLE
Installing Extension replaces "JSON" Language with "CodeTour" Language

### ISSUE THREAD

**Issue by hassanselim0** [vsls-contrib/codetour#78]
After installing the extension, the "Change Language Mode" selector now shows "CodeTour" as a language in place of "json". I'm not sure what was the intended behavior, but it caused me a lot of confusion to not find "JSON" in the list, I don't know if this means I'll get CodeTour completion suggestions in all my json files.
![image](https://user-images.githubusercontent.com/1431770/83553388-6a9b3000-a50b-11ea-9bab-509311c5e3cd.png)

**Comment by gsmile** [comment]
Thanks for filing this issue. You're right, it's confusing. We will look into fixing this!

**Comment by lostintangent** [comment]
This has no been fixed and published to the marketplace. Apologies for the unintentional bug!
