### ISSUE TITLE
Tour viewlet doesn't maintain editor's zoom factor

### ISSUE THREAD

**Issue by alpaix** [vsls-contrib/codetour#79]
Tour step snippet doesn't honor the editor's zoom level. Changing the zoom level is particularly useful in demos and presentations when a presenter is sharing their screen to make sure annotation lines are readable by others.

**Comment by gsmile** [comment]
Thanks for filing this issue! It's important to stay consistent for zoom rate. How many times do you normally zoom? Are you presenting via screenshare or projector?

**Comment by alpaix** [comment]
Recently, a few times a week, as we've got new team members. While working remotely, I've been sharing my screen via Teams.

**Comment by gsmile** [comment]
Ok great to know, thank you! We will look into prioritizing this issue.

**Comment by lostintangent** [comment]
This issue should now be fixed. Let me know if you're still running into it. Thanks!
