### ISSUE TITLE
Document deleting a step 

### ISSUE THREAD

**Issue by jsjoeio** [vsls-contrib/codetour#8]
Right now, I only see a button to end the tour. But what happens if I accidentally add a step in the wrong place or the wrong order? Currently, I have to end the tour and start over.

<img width="112" alt="image" src="https://user-images.githubusercontent.com/3806031/76168302-c8e28d80-612b-11ea-9345-91fed59d7c34.png">

If would be nice to have a button to remove the step.

**Comment by lostintangent** [comment]
Hey! I just realized I didn't document this, but you can actually edit/delete steps while you're recording a tour. These actions are exposed via the `...` menu next to the individual comment. I may need to explore other entry points to be more discoverable.

![image](https://user-images.githubusercontent.com/116461/76168548-1f50cb80-612e-11ea-9aca-8598b9e1c730.png)

**Comment by jsjoeio** [comment]
Oh, totally missed that. I changed the title. I can't add labels but if you have one for documentation and assign it to me, I'm happy to open a PR!

**Comment by lostintangent** [comment]
I added documentation for this, and also added a new `Delete Step` command to the `CodeTour` tree to make this more discoverable. Let me know if you have any further feedback. Thanks!
