### ISSUE TITLE
Square brackets in code-blocks are interpreted as CodeTour References

### ISSUE THREAD

**Issue by havogt** [vsls-contrib/codetour#82]
The following markdown for a code block 

>  \```
>  Array[]
> \```

is interpreted as a CodeTour reference and is rendered to 
```Array[#undefined](command:codetour.navigateToStep?undefined "Navigate to step #undefined")```

Extension version 0.0..32

**Comment by lostintangent** [comment]
Ah good catch! At a minimum, we should only be looking for square brackets that aren’t directly preceded  by characters. So we should be able to unblock this specific instance for sure.
