### ISSUE TITLE
Browser extensions for codetour

### ISSUE THREAD

**Issue by soneymathew** [vsls-contrib/codetour#83]
Hello folks,

Love the experience within VSCode.

Is there a plan/option to use the same json format for touring with a project hosted in github/bitbucket?

The workflow I am imagining is around authoring the tour using VSCode and playing the tour via the Browser extension **Example**: As a Chrome plugin.

I am hoping that the browser extension will maintain the state of the tour as well as enriching the DOM elements in the page with data specified in the tour.

Thanks,
Soney

**Comment by lostintangent** [comment]
Hey! Yep I’d definitely love to enable the replay experience on GitHub. We’re currently tracking this vi #10, so I’m going to close this as a duplicate. Let me know if that issue doesn’t accommodate your request, and we can reopen this. Thanks!
