### ISSUE TITLE
Broken localhost link from Codespaces

### ISSUE THREAD

**Issue by gsmile** [vsls-contrib/codetour#88]
When a dev follows a link in a tour to connect to localhost while in Codespaces (browser), the webpage it leads to is broken and user is unable to connect to localhost.

I.e. a tour step will include a link to localhost:5000 and when the dev clicks that link inside a Codespace, the link leads to a broken webpage.

**Comment by lostintangent** [comment]
This issue should now be fixed! Let me know if you're still running into issues.
