### ISSUE TITLE
Focus cursor after new step is added

### ISSUE THREAD

**Issue by jsjoeio** [vsls-contrib/codetour#9]
When I click a line to add a new step to the tour, the cursor should focus in the text input for the new step.

**Comment by lostintangent** [comment]
Agreed! I'll try to address this today.

**Comment by lostintangent** [comment]
FYI, this issue depends on a change in VS Code that’s being tracked here: https://github.com/microsoft/vscode/issues/92793. I’ll keep this open for tracking purposes, but you should watch that issue for updates/progress. Thanks!

// CC @rebornix

**Comment by rebornix** [comment]
The fix for this bug will shipped with Insiders later this week.

**Comment by lostintangent** [comment]
This has been fixed in the latest VS Code Insiders release 👍
