### ISSUE TITLE
Contribution: a GitHub Action that scans PRs for CodeTour impacts

### ISSUE THREAD

**Issue by pozil** [vsls-contrib/codetour#90]
Hi and thanks for making CodeTour available to the community, it's a great tool.

My team and I are deploying CodeTour on several projects with multiple collaborators and I want to do that at scale with some automation so I implemented a GitHub Action that scans PRs for CodeTour impacts.

The action comments on PRs to report file changes that may impact CodeTour:

![Screenshot of comment](https://github.com/pozil/codetour-watch/raw/master/docs/comment-screenshot.png)

You can find the action on the GitHub marketplace here:
https://github.com/marketplace/actions/codetour-watch

Feel free to let the other users know about this and let me know if you find this contribution useful.

**Comment by lostintangent** [comment]
This is amazing! And is unbelievably useful! Thank you so much for building this, sharing it, and of course, for trying out CodeTour! This was a key area I wanted to update soon, and so I really appreciate you contributing it 😄

**Comment by gsmile** [comment]
This looks great! Thank you for this useful contribution! :)

**Comment by lostintangent** [comment]
I just added a mention of CodeTour Watch to a new [section in the readme](https://github.com/vsls-contrib/codetour#maintaining-tours). Thanks again!
