### ISSUE TITLE
Add contributing.md or simple Dev Build section to readme.md for devs to contribute PRs

### ISSUE THREAD

**Issue by RandomFractals** [vsls-contrib/codetour#92]
vscode uses this: https://github.com/microsoft/vscode/blob/master/CONTRIBUTING.md

I use simple Dev Build section in my docs: https://github.com/RandomFractals/vscode-vega-viewer#dev-build

I think having one, or the other, or both could be helpful if you'd like see other devs contributing PRs to this repo.

P.S: I can contribute both if you'd like. Forking this repo since there are some changes I'd like to make like #91 & more :)

**Comment by lostintangent** [comment]
Just added a basic `CONTRIBUTING.md` file 👍
